### ISSUE TITLE
스택 아이템 추가 명령어 관련

### ISSUE THREAD

**Issue by pl-Steve28-lq** [nunalang/web-nuna#1]
눈, 누 명령어 처리 코드에서 v0.3 이나 v0.4 명세에 따르면

```JS
case '누': {
    recentCreated = variables.push(1) - 1
    break
}
```
를
```JS
case '누': {
    recentCreated = variables.push(getMany() || 1) - 1
    break
}
```
로 고쳐야 되지 않을까요?

v0.3 과 v0.4 의 예제의
``` 누..나..나...흐....읏..나주..거....💕 ```
부분은 20738 이 되서 오류가 나지만 웹으로 돌리니 1298 로 나와 정상 작동합니다.

예제의 눈, 누 부분을 수정한 코드
```눈나..흐.....읏..나주..거....흐...읏...
누나..나...흐....읏..나주..거....💕
눈나.....나..흐...읏나.....주거...💕
누나..흐..읏나.......주..거......응읏..

눈나..으흐읏
누나.....주..흐....읏나....응
누나.....나..주...읏나......응!
```

는 웹, 파이썬 구현에서 둘다 잘 작동하네요.

**Comment by AkiaCode** [comment]
@pmh-only

**Comment by AkiaCode** [comment]
> 눈, 누 명령어 처리 코드에서 v0.3 이나 v0.4 명세에 따르면
> 
> ```js
> case '누': {
>     recentCreated = variables.push(1) - 1
>     break
> }
> ```
> 
> 를
> 
> ```js
> case '누': {
>     recentCreated = variables.push(getMany() || 1) - 1
>     break
> }
> ```
> 
> 로 고쳐야 되지 않을까요?
> 
> v0.3 과 v0.4 의 예제의
> `누..나..나...흐....읏..나주..거....💕`
> 부분은 20738 이 되서 오류가 나지만 웹으로 돌리니 1298 로 나와 정상 작동합니다.
> 
> 예제의 눈, 누 부분을 수정한 코드
> 
> ```
> 누나..나...흐....읏..나주..거....💕
> 눈나.....나..흐...읏나.....주거...💕
> 누나..흐..읏나.......주..거......응읏..
> 
> 눈나..으흐읏
> 누나.....주..흐....읏나....응
> 누나.....나..주...읏나......응!
> ```
> 
> 는 웹, 파이썬 구현에서 둘다 잘 작동하네요.

참고로 아직 0.4는 공식 릴리즈가 아닙니다

**Comment by pmh-only** [comment]
아! 빼먹었군요\
혹시 누가 PR 남겨주실 수 있을까요...?

**Comment by pmh-only** [comment]
PR #2 에서 해결
